version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    build: ./auth
    env_file:
      - auth/.env
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  product:
    build: ./product
    env_file:
      - product/.env
    ports:
      - "3001:3001"
    volumes:
      - ./product:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - mongo
      - rabbitmq


  order:
    build: ./order
    env_file:
      - order/.env
    ports:
      - "3002:3002"
    volumes:
      - ./order:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - mongo
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-data:
